# Generated by Django 4.1.2 on 2022-11-26 11:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_consultation_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doctor_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("doctor_name", models.CharField(max_length=200)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_gender", models.CharField(max_length=10)),
                ("patient_email", models.CharField(max_length=200)),
                ("problem", models.CharField(max_length=200)),
                ("docType", models.CharField(default="C", max_length=1)),
                ("amount", models.IntegerField(default=100)),
                ("visible", models.BooleanField(default=True)),
                ("prescribed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("doctor_id", models.CharField(max_length=11)),
                ("doctor_name", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=100)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="BC", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("claimed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_user_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=200)),
                ("phoneNo", models.CharField(max_length=10)),
                ("aadharNo", models.CharField(max_length=12)),
                ("userType", models.CharField(max_length=10)),
                ("user_proof", models.ImageField(upload_to="user_proof")),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("balance", models.IntegerField(default=100000)),
                ("specialization", models.CharField(max_length=200)),
                ("experience", models.IntegerField()),
                ("doctor_proof", models.ImageField(upload_to="doctor_proof")),
                ("hospital", models.CharField(blank=True, max_length=11)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("refund", models.IntegerField(default=10)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("docType", models.CharField(default="BI", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("claimed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("document", models.CharField(default="None", max_length=64)),
                ("blockChainID", models.CharField(default="None", max_length=64)),
                ("contract_address", models.CharField(default="None", max_length=64)),
                ("hash", models.CharField(default="None", max_length=64)),
                ("previous_hash", models.CharField(default="None", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_org_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("licenseNo", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phoneNo", models.CharField(max_length=10)),
                ("orgType", models.CharField(max_length=200)),
                ("license_proof", models.ImageField(upload_to="license_proof")),
                ("org_images", models.ImageField(upload_to="org_images")),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("balance", models.IntegerField(default=1000000)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("pharmacy_id", models.CharField(max_length=11)),
                ("pharmacy_name", models.CharField(max_length=200)),
                ("medicine", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=100)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="BP", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("claimed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyOrder",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_order_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("pharmacy_id", models.CharField(max_length=11)),
                ("pharmacy_name", models.CharField(max_length=200)),
                ("medicine", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=100)),
                ("docType", models.CharField(default="O", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("delivered", models.BooleanField(default="Pending")),
            ],
        ),
        migrations.CreateModel(
            name="phoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Mobile", models.IntegerField()),
                ("isVerified", models.BooleanField(default=False)),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_prescription_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_id", models.CharField(max_length=11)),
                ("doctor_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("doctor_name", models.CharField(max_length=200)),
                ("patient_name", models.CharField(max_length=200)),
                ("medicine", models.CharField(default="None", max_length=20)),
                ("dosage", models.CharField(default="None", max_length=20)),
                ("duration", models.CharField(default="None", max_length=20)),
                ("test", models.CharField(default="None", max_length=20)),
                ("docType", models.CharField(default="P", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("medicine_bought", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_test_result_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("hospital_id", models.CharField(max_length=11)),
                ("hospital_name", models.CharField(max_length=200)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("test", models.CharField(max_length=200)),
                ("test_result", models.CharField(max_length=200)),
                ("docType", models.CharField(default="T", max_length=1)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestResultBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("hospital_id", models.CharField(max_length=11)),
                ("hospital_name", models.CharField(max_length=200)),
                ("test", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=100)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="BT", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("claimed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_user_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=200)),
                ("phoneNo", models.CharField(max_length=10)),
                ("aadharNo", models.CharField(max_length=12)),
                ("userType", models.CharField(max_length=10)),
                ("user_proof", models.ImageField(upload_to="user_proof")),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("balance", models.IntegerField(default=100000)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
    ]
