# Generated by Django 4.1.2 on 2022-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("orgType", models.CharField(max_length=200)),
                ("licenseNo", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phoneNo", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
