# Generated by Django 4.1.2 on 2022-10-25 11:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.CharField(
                default=api.models.generate_org_id,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=api.models.generate_user_id,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
