# Generated by Django 4.1.2 on 2022-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_log_last_record_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="tampered",
            field=models.BooleanField(default=False),
        ),
    ]
