# Generated by Django 4.1.2 on 2022-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_balance_alter_organization_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="phoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Mobile", models.IntegerField()),
                ("isVerified", models.BooleanField(default=False)),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
    ]
