# Generated by Django 4.1.2 on 2022-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_phonemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="balance",
            field=models.IntegerField(default=1000000),
        ),
    ]
