# Generated by Django 4.1.2 on 2022-10-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_bill_id_alter_bill_patient_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="medicines_list",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="tests_list",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicines_list",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="tests_list",
        ),
        migrations.AddField(
            model_name="bill",
            name="medicine",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="bill",
            name="test",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicine",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="prescription",
            name="test",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
