# Generated by Django 4.1.2 on 2022-10-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="dosage",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="prescription",
            name="duration",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
