# Generated by Django 4.1.2 on 2022-10-27 11:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_prescription_dosage_prescription_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("doctor_id", models.CharField(max_length=11)),
                ("doctor_name", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=1000)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="B", max_length=1)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("pharmacy_id", models.CharField(max_length=11)),
                ("pharmacy_name", models.CharField(max_length=200)),
                ("medicine", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=1000)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="B", max_length=1)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestResultBill",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bill_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("hospital_id", models.CharField(max_length=11)),
                ("hospital_name", models.CharField(max_length=200)),
                ("test", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=1000)),
                ("insurance_id", models.CharField(default="None", max_length=11)),
                ("insurance_name", models.CharField(default="None", max_length=200)),
                ("docType", models.CharField(default="B", max_length=1)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.AddField(
            model_name="consultation",
            name="amount",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="consultation",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
