# Generated by Django 4.1.2 on 2022-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_consultationbill_pharmacybill_testresultbill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationbill",
            name="amount",
            field=models.IntegerField(default=100),
        ),
    ]
