# Generated by Django 4.1.2 on 2022-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_consultationbill_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationbill",
            name="docType",
            field=models.CharField(default="BC", max_length=1),
        ),
        migrations.AlterField(
            model_name="pharmacybill",
            name="docType",
            field=models.CharField(default="BP", max_length=1),
        ),
        migrations.AlterField(
            model_name="testresultbill",
            name="docType",
            field=models.CharField(default="BT", max_length=1),
        ),
    ]
