# Generated by Django 4.1.2 on 2022-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_consultationbill_doctype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationbill",
            name="prescribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pharmacybill",
            name="docType",
            field=models.CharField(default="BP  ", max_length=1),
        ),
    ]
