# Generated by Django 4.1.2 on 2022-10-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_consultationbill_prescribed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult",
            old_name="pharmacy_id",
            new_name="hospital_id",
        ),
        migrations.RenameField(
            model_name="testresult",
            old_name="pharmacy_name",
            new_name="hospital_name",
        ),
        migrations.RenameField(
            model_name="testresult",
            old_name="test_name",
            new_name="test",
        ),
    ]
