# Generated by Django 4.1.2 on 2022-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_rename_pharmacy_id_testresult_hospital_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationbill",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testresultbill",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
    ]
