# Generated by Django 4.1.2 on 2022-10-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_consultationbill_claimed_pharmacybill_claimed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="medicine_bought",
            field=models.BooleanField(default=False),
        ),
    ]
