# Generated by Django 4.1.2 on 2022-10-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_prescription_medicine_bought"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultationbill",
            name="prescribed",
        ),
        migrations.AddField(
            model_name="consultation",
            name="prescribed",
            field=models.BooleanField(default=False),
        ),
    ]
