# Generated by Django 4.1.2 on 2022-10-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_consultationbill_prescribed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="amount",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="pharmacybill",
            name="amount",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="testresultbill",
            name="amount",
            field=models.IntegerField(default=100),
        ),
    ]
