# Generated by Django 4.1.2 on 2022-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_pharmacybill_doctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
