# Generated by Django 4.1.2 on 2022-11-09 07:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_doctor_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyOrder",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_order_id,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_id", models.CharField(max_length=11)),
                ("patient_id", models.CharField(max_length=11)),
                ("patient_name", models.CharField(max_length=200)),
                ("pharmacy_id", models.CharField(max_length=11)),
                ("pharmacy_name", models.CharField(max_length=200)),
                ("medicine", models.CharField(default="None", max_length=20)),
                ("amount", models.IntegerField(default=100)),
                ("docType", models.CharField(default="O", max_length=1)),
                ("visible", models.BooleanField(default=True)),
                ("delivered", models.BooleanField(default="Pending")),
            ],
        ),
    ]
