# Generated by Django 4.1.2 on 2022-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_pharmacyorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doctor_proof",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_proof"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user_proof",
            field=models.ImageField(blank=True, null=True, upload_to="user_proof"),
        ),
        migrations.AddField(
            model_name="organization",
            name="license_proof",
            field=models.ImageField(blank=True, null=True, upload_to="license_proof"),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_images",
            field=models.ImageField(blank=True, null=True, upload_to="org_images"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_proof",
            field=models.ImageField(blank=True, null=True, upload_to="user_proof"),
        ),
    ]
