# Generated by Django 4.1.2 on 2022-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_doctor_doctor_proof_doctor_user_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doctor_proof",
            field=models.ImageField(default="NULL", upload_to="doctor_proof"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user_proof",
            field=models.ImageField(default="NULL", upload_to="user_proof"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="license_proof",
            field=models.ImageField(default="NULL", upload_to="license_proof"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_images",
            field=models.ImageField(default="NULL", upload_to="org_images"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="user_proof",
            field=models.ImageField(default="NULL", upload_to="user_proof"),
            preserve_default=False,
        ),
    ]
