# Generated by Django 4.1.2 on 2022-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_doctor_doctor_proof_alter_doctor_user_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doctor_proof",
            field=models.ImageField(upload_to="../static/images/doctor_proof/"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user_proof",
            field=models.ImageField(upload_to="../static/images/user_proof/"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="license_proof",
            field=models.ImageField(upload_to="../static/images/license_proof/"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_images",
            field=models.ImageField(upload_to="../static/images/org_images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_proof",
            field=models.ImageField(upload_to="backend/../static/images/user_proof/"),
        ),
    ]
