# Generated by Django 4.1.2 on 2022-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_doctor_doctor_proof_alter_doctor_user_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_proof",
            field=models.ImageField(upload_to="../static/images/user_proof/"),
        ),
    ]
