# Generated by Django 4.1.2 on 2022-11-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_user_user_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doctor_proof",
            field=models.ImageField(upload_to="doctor_proof"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user_proof",
            field=models.ImageField(upload_to="user_proof"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="license_proof",
            field=models.ImageField(upload_to="license_proof"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_images",
            field=models.ImageField(upload_to="org_images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_proof",
            field=models.ImageField(upload_to="user_proof"),
        ),
    ]
