# Generated by Django 4.1.2 on 2022-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_doctor_doctor_proof_alter_doctor_user_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
