# Generated by Django 4.1.2 on 2022-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_insurancebill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("document", models.CharField(default="None", max_length=64)),
                ("blockChainID", models.CharField(default="None", max_length=64)),
                ("contract_address", models.CharField(default="None", max_length=64)),
                ("hash", models.CharField(default="None", max_length=64)),
                ("previous_hash", models.CharField(default="None", max_length=64)),
            ],
        ),
    ]
